on:
  pull_request:
    types: [ opened ]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: PullRequestHandler
      uses: shiena/GithubActions@test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
